#!/usr/bin/env sh
BASE_DIR=`dirname \$(readlink -f "\$0")`

copyright-header \
    --license-file "$BASE_DIR"/header.txt \
    --add-path cpp \
    -o . \
    --syntax "$BASE_DIR"/syntax.yml \
    "$@"

